### ISSUE TITLE
canonical is localhost

### ISSUE THREAD

**Issue by pixelfabs** [OleVik/grav-plugin-static-generator#12]
Not sure if I'm missing something. I installed a fresh Grav with Quark theme. Generated a static version and all is good. Except the canonical in the `<head>` remains http://localhost.

Am I missing something? I think it should reflect the page URL

`<link rel="canonical" href="http://localhost/typography" />`

**Comment by OleVik** [comment]
Do you have any special settings set in `system.yaml`? Typically, `absolute_urls` must be `false`. In testing I get `<link rel="canonical" href="http://localhost/typography" />` from a normal `php bin/plugin static-generator page` on a fresh installation.

The way most themes are constructed, [including Quark](https://github.com/getgrav/grav-theme-quark/blob/2.0.3/templates/partials/base.html.twig#L17), and because of how [Grav handles custom base URLs](https://github.com/getgrav/grav/blob/1.6.31/system/src/Grav/Common/Uri.php#L134-L150), there's little room for overriding the domain used in canonicals. Only setting `custom_base_url` to a fully qualified URL will do it.

Are you looking to rewrite the `http://localhost` part of the canonical?

**Comment by OleVik** [comment]
Should be solved by [v4](https://github.com/OleVik/grav-plugin-static-generator/releases/tag/4.0.0).
